import Head from "next/head";
import Image from "next/image";
import { Inter, Manrope, Open_Sans } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";
import Featarticle from "@/Components/Navbar/FeaturedArticle/Featarticle";
import NewsArticle from "@/Components/Navbar/FeaturedArticle/NewsArticle/NewsArticle";
import Footer from "@/Components/Footer/Footer";
import NewsLetter from "@/Components/Newsletter/NewsLetter";
import Slider from "@/Components/Slider/Slider";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });
const opensans = Open_Sans({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${manrope.className} ${opensans.className}`}>
        <Navbar />
        <Featarticle />
        <NewsArticle />
        <NewsLetter />
        <Footer />
        {/* <Slider /> */}
      </main>
    </>
  );
}
